experiment_name: gan_mnist
dataset_name: "MNIST"
model_name: "GAN"
dataroot: ""
num_workers: 1
batch_size: 128
num_epochs: 4
num_channels: 1
z_size: 100
num_G_features: 64
num_D_features: 64
image_size: 64
num_layers: 0
learning_rate: 1e-3
beta1: 0.5
beta2: 0.999
seed: 1234
shuffle: 1
ngpu: 0