experiment_name: vae_mnist
dataset_name: "MNIST"
model_name: "VAE"
num_workers: 1
batch_size: 128
num_epochs: 4
num_channels: 1
loader: MNISTDataLoader
image_size: 64
num_layers: 0
learning_rate: 1e-3
shuffle: 1
ngpu: 0
print_every: 50